Replace tabs with 4 spaces

diff --git a/CNI/romana b/CNI/romana
--- a/CNI/romana
+++ b/CNI/romana
@@ -52,12 +52,12 @@ get_iface_name     () { A=$(ip ro show $1 | awk '{ print $3 }'); echo ${A}; }
 log                () { echo "$*"; }
 log_env            () { env; }
 die () {
-	echo $1
-	# Restore stdout - before reporting an error to Kube
-	exec 1>&6
+    echo $1
+    # Restore stdout - before reporting an error to Kube
+    exec 1>&6
 
-	printf '{ "Error": "%s" }' "$1"
-	exit $2
+    printf '{ "Error": "%s" }' "$1"
+    exit $2
 }
 
 trap "die 'CNI plugin - Unexpected error'" EXIT
@@ -65,7 +65,7 @@ trap "die 'CNI plugin - Unexpected error'" EXIT
 # -- Config
 # Kubernetes pases config via stdin
 while read line; do 
-	INPUT="$INPUT$line"
+    INPUT="$INPUT$line"
 done
 
 # Looping over top level json keys
@@ -77,24 +77,24 @@ for k in $(echo $INPUT | jq -r 'keys[]'); do
         kubectl_binary)
                 KUBECTL=$(get_config_item $k)
                 ;;
-	ipam)
-		[[ $(get_config_item $k.type) == "romana-ipam" ]] || die  "Bad ipam - only romana-ipam is supported"
-		;;
-	kube_master_ip)
-		KUBE_MASTER_IP=$(get_config_item $k)
-		;;
-	kubectl_args)
-		KUBEARGS=$(get_config_item $k)
-		;;
-	romana_master_url)
-		ROMANA_MASTER_URL=$(get_config_item $k)
-		;;
-	romana_cli_config)
-		ROMANA_CLI="$ROMANA_CLI -c $(get_config_item $k)"
-		;;
-	segment_label_name)
-		SEGMENT_LABEL_NAME=$(get_config_item $k)
-		;;
+    ipam)
+        [[ $(get_config_item $k.type) == "romana-ipam" ]] || die  "Bad ipam - only romana-ipam is supported"
+        ;;
+    kube_master_ip)
+        KUBE_MASTER_IP=$(get_config_item $k)
+        ;;
+    kubectl_args)
+        KUBEARGS=$(get_config_item $k)
+        ;;
+    romana_master_url)
+        ROMANA_MASTER_URL=$(get_config_item $k)
+        ;;
+    romana_cli_config)
+        ROMANA_CLI="$ROMANA_CLI -c $(get_config_item $k)"
+        ;;
+    segment_label_name)
+        SEGMENT_LABEL_NAME=$(get_config_item $k)
+        ;;
         esac
 done
 
@@ -113,17 +113,17 @@ log "$*"
 log_env
 
 result () {
-	ip=$1
-	mask=$2
-	printf '{ "cniVersion": "0.1.0", "ip4": { "ip": "%s/%s" } }' $ip $mask
+    ip=$1
+    mask=$2
+    printf '{ "cniVersion": "0.1.0", "ip4": { "ip": "%s/%s" } }' $ip $mask
 }
 
 req () {
-	# TODO currently romana agent expects valid mac address on k8s endpoint even though it not needed there
-	iface=$1
-	ip=$2
-	ns_isloation=$3
-	printf '{ "net_if" : { "interface_name": "%s", "mac_address": "de:ad:be:ef:00:00", "ip_address" : "%s" }, "options" : { "namespace_isolation" : "%s"} }' $iface $ip $ns_isloation
+    # TODO currently romana agent expects valid mac address on k8s endpoint even though it not needed there
+    iface=$1
+    ip=$2
+    ns_isloation=$3
+    printf '{ "net_if" : { "interface_name": "%s", "mac_address": "de:ad:be:ef:00:00", "ip_address" : "%s" }, "options" : { "namespace_isolation" : "%s"} }' $iface $ip $ns_isloation
 }
 
 find_romana_service() {
@@ -144,13 +144,13 @@ find_romana_id () {
     field_name=$2
     field_value=$3
     if [[ "$entity_type" == "tenant" ]]; then
-	svc = "tenant"
+    svc = "tenant"
     elif [[ "$entity_type" == "segment" ]]; then
-  	svc = "tenant"
+      svc = "tenant"
     elif [[ "$entity_type" == "host" ]]; then
-  	svc = "topology"
+      svc = "topology"
     else
-	trap "Don't know how to deal with $entity_type." EXIT
+    trap "Don't know how to deal with $entity_type." EXIT
     fi
     svc_url=$(find_romana_service svc)
     find_url="${svc_url}/findExactlyOne/${entity_type}s?${field_name}=${field_value}"
@@ -159,129 +159,129 @@ find_romana_id () {
 }
 
 ipam_allocate_ip () {
-	# CNI expects us to read ipam config from stdin, but for demo config is static anyway.
-	tenant=$1
-	segment=$2
-	node=$3
-	romana_tenant_id=$(find_romana_id 'tenant' 'external_id' tenant)
+    # CNI expects us to read ipam config from stdin, but for demo config is static anyway.
+    tenant=$1
+    segment=$2
+    node=$3
+    romana_tenant_id=$(find_romana_id 'tenant' 'external_id' tenant)
         romana_segment_id=$(find_romana_id'segment' 'name' segment)
         romana_host_id=$(find_romana_id 'host' 'name' node)
         ipam_service_url=$(find_romana_service 'ipam')
         url="${ipam_service_url}/endpoints"
-	payload="{\"tenant_id\" : ${romana_tenant_id}, \"segment_id\' : ${romana_segment_id}, \"host_id\" : ${romana_host_id} }"
-	ip=`curl -H 'content-type: application/json' -X POST -d $payload | jq '.ip'`
-	echo $ip
+    payload="{\"tenant_id\" : ${romana_tenant_id}, \"segment_id\' : ${romana_segment_id}, \"host_id\" : ${romana_host_id} }"
+    ip=`curl -H 'content-type: application/json' -X POST -d $payload | jq '.ip'`
+    echo $ip
 }
 
 set_up_pod () {
-	# Getting additional information from kubernetes
-	log "--- ADD --"
-	NSPID=$(get_nspid "$CNI_NETNS")
-	log "--- nspid = $NSPID ---"
-	POD=$(get_args | get_pod)
-	log "--- POD = $POD ---"
-	NAMESPACE=$(get_args | get_pod_ns)
-	log "--- NAMESPACE = $NAMESPACE ---"
-	KUBEARGS="$KUBEARGS --namespace=$NAMESPACE"
-#	TENANT=$( $KUBECTL $KUBEARGS describe pod $POD | get_labels | get_tenant )
-#	log "--- TENANT = $TENANT ---"
-	SEGMENT=$( $KUBECTL $KUBEARGS get pod $POD -o json | jq -r 'if .metadata.labels["'$SEGMENT_LABEL_NAME'"] then .metadata.labels["'$SEGMENT_LABEL_NAME'"] else empty end')
-	[[ $SEGMENT ]] || SEGMENT="default"
-	log "--- SEGMENT = $SEGMENT ---"
-	NODE=$( $KUBECTL $KUBEARGS get pod "$POD" -o json | jq -r '.spec.nodeName')
-	log "--- NODE = $NODE ---"
-	NS_ISOLATION="off"
-	# The metadata value for isolation is now a JSON object. Since we ask kubectl to give us namespace data in JSON, we need two steps to extract it.
-	# Extract the network policy from the namespace annotation. Capture the value.
-	NS_POLICY=$( $KUBECTL $KUBEARGS get namespace $NAMESPACE -o json | jq -r '.metadata.annotations["net.beta.kubernetes.io/networkpolicy"] // empty')
-	if [[ "$NS_POLICY" ]]; then
-		# We have a value. Try to extract the ingress -> isolation field.
-		INGRESS_ISOLATION=$(jq -r '.ingress.isolation // empty' <<< "$NS_POLICY")
-		if [[ "$INGRESS_ISOLATION" = "DefaultDeny" ]]; then
-			# Field was present and matched the known "DefaultDeny" value. Enable isolation.
-			NS_ISOLATION="on"
-		fi
-	fi
-	log "--- NS_ISOLATION = $NS_ISOLATION ---"
+    # Getting additional information from kubernetes
+    log "--- ADD --"
+    NSPID=$(get_nspid "$CNI_NETNS")
+    log "--- nspid = $NSPID ---"
+    POD=$(get_args | get_pod)
+    log "--- POD = $POD ---"
+    NAMESPACE=$(get_args | get_pod_ns)
+    log "--- NAMESPACE = $NAMESPACE ---"
+    KUBEARGS="$KUBEARGS --namespace=$NAMESPACE"
+#    TENANT=$( $KUBECTL $KUBEARGS describe pod $POD | get_labels | get_tenant )
+#    log "--- TENANT = $TENANT ---"
+    SEGMENT=$( $KUBECTL $KUBEARGS get pod $POD -o json | jq -r 'if .metadata.labels["'$SEGMENT_LABEL_NAME'"] then .metadata.labels["'$SEGMENT_LABEL_NAME'"] else empty end')
+    [[ $SEGMENT ]] || SEGMENT="default"
+    log "--- SEGMENT = $SEGMENT ---"
+    NODE=$( $KUBECTL $KUBEARGS get pod "$POD" -o json | jq -r '.spec.nodeName')
+    log "--- NODE = $NODE ---"
+    NS_ISOLATION="off"
+    # The metadata value for isolation is now a JSON object. Since we ask kubectl to give us namespace data in JSON, we need two steps to extract it.
+    # Extract the network policy from the namespace annotation. Capture the value.
+    NS_POLICY=$( $KUBECTL $KUBEARGS get namespace $NAMESPACE -o json | jq -r '.metadata.annotations["net.beta.kubernetes.io/networkpolicy"] // empty')
+    if [[ "$NS_POLICY" ]]; then
+        # We have a value. Try to extract the ingress -> isolation field.
+        INGRESS_ISOLATION=$(jq -r '.ingress.isolation // empty' <<< "$NS_POLICY")
+        if [[ "$INGRESS_ISOLATION" = "DefaultDeny" ]]; then
+            # Field was present and matched the known "DefaultDeny" value. Enable isolation.
+            NS_ISOLATION="on"
+        fi
+    fi
+    log "--- NS_ISOLATION = $NS_ISOLATION ---"
 
-	# Ensure segment exists
-	log "-- Ensuring segment for tenant $NAMESPACE --"
-	SEGMENT_CHECK=$($ROMANA_CLI segment list $NAMESPACE -f json | jq -r --arg seg $SEGMENT  'if . != 0 then (reverse|.[0] |.Segments[] | if .name==$seg then "OK" else empty end) else empty end')
-	if ! [[ $SEGMENT_CHECK ]]; then
-		log "--- SEGMENT $SEGMENT does not exist - creating ---"
-		$ROMANA_CLI segment add $NAMESPACE $SEGMENT -i $SEGMENT
-	else
-		log "--- SEGMENT $SEGMENT exists ---"
-	fi
+    # Ensure segment exists
+    log "-- Ensuring segment for tenant $NAMESPACE --"
+    SEGMENT_CHECK=$($ROMANA_CLI segment list $NAMESPACE -f json | jq -r --arg seg $SEGMENT  'if . != 0 then (reverse|.[0] |.Segments[] | if .name==$seg then "OK" else empty end) else empty end')
+    if ! [[ $SEGMENT_CHECK ]]; then
+        log "--- SEGMENT $SEGMENT does not exist - creating ---"
+        $ROMANA_CLI segment add $NAMESPACE $SEGMENT -i $SEGMENT
+    else
+        log "--- SEGMENT $SEGMENT exists ---"
+    fi
 
-	# Asking romana ipam for an IP address, based on `tenant` label.
-	log "--- PRE-IPAM ---"
-	[[ $SEGMENT ]] || SEGMENT=default
-	IP=$(ipam_allocate_ip $NAMESPACE $SEGMENT $NODE)
-	log "--- POST-IPAM IP=$IP---"
-	[[ $IP ]] || die "Failed to allocate IP address for pod $POD on node $NODE with tenant $NAMESPACE" 2
+    # Asking romana ipam for an IP address, based on `tenant` label.
+    log "--- PRE-IPAM ---"
+    [[ $SEGMENT ]] || SEGMENT=default
+    IP=$(ipam_allocate_ip $NAMESPACE $SEGMENT $NODE)
+    log "--- POST-IPAM IP=$IP---"
+    [[ $IP ]] || die "Failed to allocate IP address for pod $POD on node $NODE with tenant $NAMESPACE" 2
 
-	# Setting up the networking for Infra namespace
-	sudo ip link add "veth0-${NSPID}" type veth peer name "veth1-${NSPID}"
-	sudo ip link set "veth1-${NSPID}" netns ${NSPID}
-	sudo nsenter -t ${NSPID} -n ip link set "veth1-${NSPID}" name eth0
-	sudo nsenter -t ${NSPID} -n ip link set eth0 up
-	sudo nsenter -t ${NSPID} -n ip addr add $IP/32 dev eth0
-	sudo nsenter -t ${NSPID} -n ip ro add $GATE_SRC dev eth0
-	sudo nsenter -t ${NSPID} -n ip ro add default via $GATE_SRC dev eth0
-	sudo ip link set "veth0-${NSPID}" up
+    # Setting up the networking for Infra namespace
+    sudo ip link add "veth0-${NSPID}" type veth peer name "veth1-${NSPID}"
+    sudo ip link set "veth1-${NSPID}" netns ${NSPID}
+    sudo nsenter -t ${NSPID} -n ip link set "veth1-${NSPID}" name eth0
+    sudo nsenter -t ${NSPID} -n ip link set eth0 up
+    sudo nsenter -t ${NSPID} -n ip addr add $IP/32 dev eth0
+    sudo nsenter -t ${NSPID} -n ip ro add $GATE_SRC dev eth0
+    sudo nsenter -t ${NSPID} -n ip ro add default via $GATE_SRC dev eth0
+    sudo ip link set "veth0-${NSPID}" up
 
-	log "$(req "veth0-${NSPID}" "$IP" "$NS_ISOLATION")"
-	# Romana agent does the rest (endpoint route and firewall)
-	agent_port=$(find_agent_port)
-	curl -s -H 'content-type: application/json' -XPOST -d "$(req "veth0-${NSPID}" "$IP" "$NS_ISOLATION")" http://localhost:${agent_port}/pod 2>&1 >> $LOGFILE
+    log "$(req "veth0-${NSPID}" "$IP" "$NS_ISOLATION")"
+    # Romana agent does the rest (endpoint route and firewall)
+    agent_port=$(find_agent_port)
+    curl -s -H 'content-type: application/json' -XPOST -d "$(req "veth0-${NSPID}" "$IP" "$NS_ISOLATION")" http://localhost:${agent_port}/pod 2>&1 >> $LOGFILE
 
-	log "$(req "veth0-${NSPID}" "$IP" "$NS_ISOLATION")"
-	log "--- Setup with infra pod = $POD pid = $PID, PEERIFx = $PEERIFx, PEERIFn=$PEERIFn, TENANT=$NAMESPACE, NODE=$NODE, IP=$IP"
-	R=$(result "$IP" "$GATE_MASK")
-	log "$R"
+    log "$(req "veth0-${NSPID}" "$IP" "$NS_ISOLATION")"
+    log "--- Setup with infra pod = $POD pid = $PID, PEERIFx = $PEERIFx, PEERIFn=$PEERIFn, TENANT=$NAMESPACE, NODE=$NODE, IP=$IP"
+    R=$(result "$IP" "$GATE_MASK")
+    log "$R"
 
-	# Restore stdout - ready to talk back to kubernetes
-	exec 1>&6
+    # Restore stdout - ready to talk back to kubernetes
+    exec 1>&6
 
-	# Kubernetes expects valid json on output so no one above should echo anything in stdout
-	echo -n $R
+    # Kubernetes expects valid json on output so no one above should echo anything in stdout
+    echo -n $R
 }
 
 pod_down () {
-	POD=$(get_args | get_pod)
-	log "--- POD = $POD ---"
-	NAMESPACE=$(get_args | get_pod_ns)
-	log "--- NAMESPACE = $NAMESPACE ---"
-	KUBEARGS="$KUBEARGS --namespace=$NAMESPACE"
-	log "--- KUBEARGS = $KUBEARGS ---"
-	POD_IP=$( $KUBECTL $KUBEARGS get pod $POD -o json | jq -r '.status.podIP' )
-	log "--- POD_IP = ${POD_IP} ---"
-	IFACE=$( get_iface_name "$POD_IP" )
-	log "--- IFACE = ${IFACE} ---"
+    POD=$(get_args | get_pod)
+    log "--- POD = $POD ---"
+    NAMESPACE=$(get_args | get_pod_ns)
+    log "--- NAMESPACE = $NAMESPACE ---"
+    KUBEARGS="$KUBEARGS --namespace=$NAMESPACE"
+    log "--- KUBEARGS = $KUBEARGS ---"
+    POD_IP=$( $KUBECTL $KUBEARGS get pod $POD -o json | jq -r '.status.podIP' )
+    log "--- POD_IP = ${POD_IP} ---"
+    IFACE=$( get_iface_name "$POD_IP" )
+    log "--- IFACE = ${IFACE} ---"
 
-	log "$(req "${IFACE}" "$IP" "$NS_ISOLATION")"
-	# Romana agent does the rest (endpoint route and firewall)
-	curl -s -XDELETE -H 'content-type: application/json' -d "$(req "${IFACE}" "$POD_IP")" http://localhost:9604/pod 2>&1 >> $LOGFILE
+    log "$(req "${IFACE}" "$IP" "$NS_ISOLATION")"
+    # Romana agent does the rest (endpoint route and firewall)
+    curl -s -XDELETE -H 'content-type: application/json' -d "$(req "${IFACE}" "$POD_IP")" http://localhost:9604/pod 2>&1 >> $LOGFILE
 
-	# Deallocate ip address
-	curl -s -XDELETE "http://$ROMANA_MASTER_IP:9601/endpoints/$POD_IP"
+    # Deallocate ip address
+    curl -s -XDELETE "http://$ROMANA_MASTER_IP:9601/endpoints/$POD_IP"
 
-	# Restore stdout - ready to talk back to kubernetes
-	exec 1>&6
+    # Restore stdout - ready to talk back to kubernetes
+    exec 1>&6
 }
 
 case $CNI_COMMAND in
-	ADD)
-		set_up_pod
-		;;
-	DEL)
-		pod_down
-		;;
-	STATUS)
-		# Not implemented in kubernetes yet
-		:
-		;;
+    ADD)
+        set_up_pod
+        ;;
+    DEL)
+        pod_down
+        ;;
+    STATUS)
+        # Not implemented in kubernetes yet
+        :
+        ;;
 esac
 # normal exit shouldn't trigger trap
 trap - EXIT
